version: '3.8'

services:
    postgres:
        image: 'postgres:latest'
        restart: always
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            PGDATA: /var/lib/postgresql/data/pgdata
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U $${DB_USERNAME}']
            retries: 3
            timeout: 5s
